"""add models CreateEvent and Bet

Revision ID: 633a9422d128
Revises: cb16da1fec46
Create Date: 2024-03-15 15:00:48.588629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633a9422d128'
down_revision = 'cb16da1fec46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
